### ISSUE TITLE
WindowLeaked

### ISSUE THREAD

**Issue by ericn37** [carnivalmobile/carnival-android-sdk#5]
I'm using Carnival 3.3.5.

Play Services and Firebase versions:
```
compile 'com.google.android.gms:play-services-base:9.2.0'
    compile 'com.google.android.gms:play-services-location:9.2.0'
    compile 'com.google.android.gms:play-services-gcm:9.2.0'
    compile 'com.google.firebase:firebase-core:9.2.0'
    compile 'com.google.firebase:firebase-messaging:9.2.0'
```

Full stacktrace:
```
09-14 14:13:39.179 24454-24454/? E/WindowManager: android.view.WindowLeaked: Activity com.sephora.digital.views.activities.SplashActivity has leaked window android.widget.FrameLayout{83f67f1 V.E...... ......ID 0,0-1080,279} that was originally added here
                                                      at android.view.ViewRootImpl.<init>(ViewRootImpl.java:372)
                                                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
                                                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
                                                      at com.carnival.sdk.InAppNotification.setVisible(InAppNotification.java:295)
                                                      at com.carnival.sdk.InAppNotification.access$1700(InAppNotification.java:47)
                                                      at com.carnival.sdk.InAppNotification$3.onPostExecute(InAppNotification.java:290)
                                                      at com.carnival.sdk.InAppNotification$3.onPostExecute(InAppNotification.java:269)
                                                      at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                      at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                      at android.os.Looper.loop(Looper.java:234)
                                                      at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by viperwarp** [comment]
Hi @ericn37, thanks for raising this. We are just looking into this on our end and will be in touch once we have more info or a release timeframe.
